products:
  - code: "480"
    description: "COUVE KG"
    ncm: "07049000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "490"
    description: "ALFACE KG"
    ncm: "07051900"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "3"
    description: "ALFACE UNI"
    ncm: "07051900"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "13"
    description: "CEBOLINHA"
    ncm: "07039090"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "24"
    description: "SALSA"
    ncm: "07099990"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "48"
    description: "CEBOLA BRANCA"
    ncm: "07122000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "61"
    description: "PIMENTÃO VERDE"
    ncm: "07096000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "39"
    description: "BATATA INGLESA"
    ncm: "07019000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "46"
    description: "BETERRABA"
    ncm: "07069000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "127"
    description: "LIMÃO"
    ncm: "08055000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "87"
    description: "ABACAXI"
    ncm: "08043000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "76"
    description: "PEPINO"
    ncm: "07070000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "66"
    description: "PENTE DE OVOS"
    ncm: "04072100"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "95"
    description: "BANANA CATURRA"
    ncm: "08031000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "55"
    description: "MANDIOCA"
    ncm: "07141000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "136"
    description: "MAMÃO FORM"
    ncm: "08072000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "120"
    description: "LARANJA"
    ncm: "08051000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "31"
    description: "ALHO SEM CASCA"
    ncm: "07032010"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "86"
    description: "VAGEM"
    ncm: "07082000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "146"
    description: "MANGA PALMER"
    ncm: "08045020"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "10"
    description: "COUVE"
    ncm: "07049000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "50"
    description: "CHUCHU"
    ncm: "07099990"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "128"
    description: "MELÂNCIA"
    ncm: "08071100"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "17"
    description: "HORTELÃ"
    ncm: "07099990"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "19"
    description: "MANJERICÃO"
    ncm: "07099990"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "34"
    description: "ABÓB ITALIANA"
    ncm: "07099990"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "141"
    description: "MAÇA FUJI"
    ncm: "08081000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "49"
    description: "CENOURA"
    ncm: "07061000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "79"
    description: "REPOLHO VERDE"
    ncm: "07049000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "7"
    description: "ALMEIRÃO"
    ncm: "07051900"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "82"
    description: "TOMATE"
    ncm: "07020000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "80"
    description: "REPOLHO ROXO"
    ncm: "07049000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "263"
    description: "ÁGUA MINERAL IG 20L"
    ncm: "22011000"
    cfop: "5405"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "150"
    description: "MELÃO"
    ncm: "08071900"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "45"
    description: "BERINJELA"
    ncm: "07093000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "47"
    description: "CEBOLA ROXA"
    ncm: "07031019"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "178"
    description: "UVA S/ SEMENTE"
    ncm: "08061000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "37"
    description: "ABÓBORA MORANGA"
    ncm: "07099300"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "78"
    description: "QUIABO"
    ncm: "07089000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "115"
    description: "KIWI"
    ncm: "08105000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "135"
    description: "MORANGO BANDEJA"
    ncm: "08101000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "62"
    description: "PIMEN VL/AMAR"
    ncm: "07096000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "41"
    description: "BATATA MIÚDA"
    ncm: "07019000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "468"
    description: "ALHO PORO"
    ncm: "07039090"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "43"
    description: "BATATA DOCE"
    ncm: "07142000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "30"
    description: "ALHO COM CASCA"
    ncm: "07032010"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "132"
    description: "LIMÃO SICILIANO"
    ncm: "08055000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "97"
    description: "BANANA MAÇA"
    ncm: "08031000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "112"
    description: "COCA COLA 2L RETOR"
    ncm: "22021000"
    cfop: "5405"
    icms: "6500"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "780"
    description: "CEREJA"
    ncm: "08092900"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "28"
    description: "ALFACE ROXA"
    ncm: "07051900"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "781"
    description: "ALFACE ROXA KG"
    ncm: "07051900"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "4"
    description: "ALFACE AMERICANA"
    ncm: "07051900"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "782"
    description: "ALFACE AMERIC KG"
    ncm: "07051100"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "54"
    description: "JILÓ"
    ncm: "07099990"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "64"
    description: "TAXA DE ENTREGA"
    ncm: "49019900"  
    cfop: "5949"  
    icms: "400"  
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "65"
    description: "PRODUTO EM PROMOÇÃO"
    ncm: "21069090"  
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "1124"  
    description: "SACO DE MILHO"
    ncm: "10059090"  
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"  
    unidade_tributavel: "UN"
  - code: "159"  
    description: "PÊRA PORTUGUESA"
    ncm: "08083000"  
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"  
    unidade_tributavel: "KG"
  - code: "160"  
    description: "PÊRA WILLIANS"
    ncm: "08083000"  
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"  
    unidade_tributavel: "KG"
  - code: "56"  
    description: "BAROA"
    ncm: "07149000"  
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"  
    unidade_tributavel: "KG"
  - code: "100"  
    description: "BANANA PRATA"
    ncm: "08039000"  
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"  
    unidade_tributavel: "KG"
  - code: "91"  
    description: "AMEIXA NACIONAL"
    ncm: "08094000"  
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"  
    unidade_tributavel: "KG"
  - code: "92"  
    description: "PÊSSEGO"
    ncm: "08093010"  
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"  
    unidade_tributavel: "KG"
  - code: "8"  
    description: "BRÓCOLIS JAPONÊS"
    ncm: "07041000"  
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"  
    unidade_tributavel: "KG"
  - code: "16"  
    description: "ESPINAFRE"
    ncm: "07097000"  
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"  
    unidade_tributavel: "KG"
  - code: "142"  
    description: "MAÇA GALA"
    ncm: "08081000"  
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"  
    unidade_tributavel: "KG"
  - code: "143"  
    description: "MAÇA MIÚDA"
    ncm: "08081000"  
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"  
    unidade_tributavel: "KG"
  - code: "166"  
    description: "UVA ROSADA"
    ncm: "08061000"  
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"  
    unidade_tributavel: "KG"
  - code: "140"  
    description: "MAÇA ARGENTINA"
    ncm: "08081000"  
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"  
    unidade_tributavel: "KG"
  - code: "264"
    description: "AGUA S/GAS 500ML FD"
    ncm: "22011000"
    cfop: "5405"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "265"
    description: "ÁGUA C/GAS 500ML FD"
    ncm: "22011000"
    cfop: "5405"
    icms: "102"
    unidade_comercial: "UN"  
    unidade_tributavel: "UN"
  - code: "153"
    description: "MEXERICA POKAN"
    ncm: "08052100"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "15"
    description: "ACELGA UNI"
    ncm: "07049000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "18"
    description: "MOSTARDA"
    ncm: "07099990"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "12"
    description: "COUVE FLOR"
    ncm: "07041000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "51"
    description: "CARÁ"
    ncm: "07143000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "113"
    description: "GOIABA"
    ncm: "08044000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "133"
    description: "MARACUJÁ"
    ncm: "08104000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "6"
    description: "AGRIÃO"
    ncm: "07049000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "495"
    description: "ÁGUA MINERAL COPO"
    ncm: "22011000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "144"
    description: "MILHO ESPIGA"
    ncm: "07099990"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "101"
    description: "BANANA DA TERRA"
    ncm: "08031000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "102"
    description: "RÚCULA"
    ncm: "07049000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "9"
    description: "RABANETE"
    ncm: "07069000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
  - code: "52"
    description: "AÇAFRÃO"
    ncm: "09103000"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "KG"
    unidade_tributavel: "KG"
  - code: "001"
    description: "PRODUTO CORINGA"
    ncm: "07099990"
    cfop: "5102"
    icms: "102"
    unidade_comercial: "UN"
    unidade_tributavel: "UN"
